template = "bitmask/slice-32x32-diagonals"

[positions]
convex = 0
horizontal = 1
vertical = 2
concave = 3
flat = 4

[icon_size]
x = 40
y = 40

[output_icon_size]
x = 40
y = 40

[cut_pos]
x = 20
y = 20